title: "323实验室服务器主页"
email:
description: >-
  323实验室 CPU 服务器使用说明

minimal_mistakes_skin: default
search: true

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.28.0"

permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

lang: zh-CN
locale: "zh_CN"
timezone: "Asia/Shanghai"
date_format: "%Y年%m月%d日"

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "323实验室"
  avatar: "/assets/images/lab_logo.png"
  bio: "实验室计算服务器使用说明"
  links:
    - label: "Hefei, CN"
      icon: "fa-solid fa-location-dot"
      url: "https://www.google.com/maps/place/Hefei,+Anhui,+China/"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: true
      toc: true
      toc_sticky: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
